---
title: Peanut Butter Banana Oat Pancakes
subtitle: Use up those mushy bananas 🍌
toc: true
toc-depth: 6
---
<!--___________________________________________________________________|
|______________________________________________________________________|
|        _   __   _   _ _   _   _   _         _                        |
|   |   |_| | _  | | | V | | | | / |_/ |_| | /                         |
|   |__ | | |__| |_| |   | |_| | \ |   | | | \_                        |
|    _  _         _ ___  _       _ ___   _                    / /      |
|   /  | | |\ |  \   |  | / | | /   |   \                    (^^)      |
|   \_ |_| | \| _/   |  | \ |_| \_  |  _/                    (____)o   |
|______________________________________________________________________|
|______________________________________________________________________|
|                                                                      |
|----------------------------------------------------------------------|
|   Copyright 2026, Rebecca Rashkin                                    |
|   -------------------------------                                    |
|   This code may be copied, redistributed, transformed, or built      |
|   upon in any format for educational, non-commercial purposes.       |
|                                                                      |
|   Please give me appropriate credit should you choose to use this    |
|   resource. Thank you :)                                             |
|----------------------------------------------------------------------|
|                                                                      |
|______________________________________________________________________|
|   //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\   |
|____________________________________________________________________-->
<!--DESCRIPTION
|   Banana pancake recipe
|____________________________________________________________________-->

```text
Author: Rebecca
Yield:  ~10 pancakes
```

## Software

### Dry Ingredients

Qty | Ingredient
-|-
`1 c`     | Rolled oats
`1/4 c`   | Peanut butter powder
`1 tsp`   | Pumpkin pie spice or cinnamon
`1/4 tsp` | Salt
`1 tsp`   | Baking soda*

\* See notes.

### Wet Ingredients

Qty | Ingredient
-|-
`3`       | Overripe bananas
`2`       | Eggs
`2 Tbsp`  | Almond milk*
`1 Tbsp`  | Vanilla extract
`1 tsp`   | Vinegar or lemon juice*

 \* See notes.

### Additional Ingredients

Measure these with your ♥️

- Butter/oil for cooking, topping
- Maple syrup

## Hardware

```text
Griddle
Turner
```

## Procedure

1. Preheat griddle to medium low heat (~3/10).
1. Blend oats into flour. Combine all dry ingredients.
1. Blend wet ingredients.
1. Combine wet and dry ingredients.
1. Pour on griddle in `~1/3 c` portions.
1. Cook on each side for 2-3 minutes.
1. Serve with butter/coconut oil/maple syrup as desired.

## Notes

1. You can replace the baking soda and vinegar with `1 tsp` baking powder.
1. Almond milk can be substituted with water or any kind of milk.