---
title: Full-Time Work Schedule Sourdough
subtitle: Weeknight sourdough is possible!
toc: true
toc-depth: 6
---
<!--___________________________________________________________________|
|______________________________________________________________________|
|        _   __   _   _ _   _   _   _         _                        |
|   |   |_| | _  | | | V | | | | / |_/ |_| | /                         |
|   |__ | | |__| |_| |   | |_| | \ |   | | | \_                        |
|    _  _         _ ___  _       _ ___   _                    / /      |
|   /  | | |\ |  \   |  | / | | /   |   \                    (^^)      |
|   \_ |_| | \| _/   |  | \ |_| \_  |  _/                    (____)o   |
|______________________________________________________________________|
|______________________________________________________________________|
|                                                                      |
|----------------------------------------------------------------------|
|   Copyright 2026, Rebecca Rashkin                                    |
|   -------------------------------                                    |
|   This code may be copied, redistributed, transformed, or built      |
|   upon in any format for educational, non-commercial purposes.       |
|                                                                      |
|   Please give me appropriate credit should you choose to use this    |
|   resource. Thank you :)                                             |
|----------------------------------------------------------------------|
|                                                                      |
|______________________________________________________________________|
|   //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\   |
|____________________________________________________________________-->
<!--DESCRIPTION
|   Sourdough recipe
|____________________________________________________________________-->

```text
Author: Rebecca
Yield:  2 loaves
```

I'm a software engineer and work 9 hour days so I have been
experimenting with process to figure out a consistent way to feasibly
bake sourdough sandwich bread within the constraints of my work
schedule.

The process here might be a little less traditional (e.g. longer proof after refrigeration), but I've been getting great results and it works for my schedule.

## General

### Notes

1. Quantities for 1 loaf are in parentheses `()`.
2. For a variation, replace salt with `0.75 c (6 Tbsp)` of 'everything
   bagel' seasoning.
   - I use the Kirkland brand which contains `65 mg` sodium per `1/4 tsp`
   seasoning.

### Software

Qty | Ingredient
-|-
`300 g  (150 g)`  | Happy starter or [levain](#reactivating-starter)
`3 c    (1 1/2 c)`| Filtered water
`1000 g (500 g)`  | All purpose or bread flour
`24 g   ( 12 g)`  | Salt**
`~ 2 qt`          | Boiling water to generate steam*

\* Boiling water is necessary only if _not_ using the double-pan method.

#### Variation 1: Everything Bagel

** Substitute salt with `0.75 c (6 Tbsp for one loaf)` everything bagel seasoning.

#### Variation 2: Rosemary Garlic

__Note:__ In all of my attempts to make rosemary sourdough, the loaf never seems to rise enough. I recently learned that this is likely due to the antimicrobial properties of rosemary. So basically the rosemary kills my yeast 😧 I think it's because I add the rosemary too early in the process - perhaps if I add it right before I shape the loaf it will turn out better. So, add rosemary at your own risk 🫣

In any case, this the appropriate amount to add:

Qty | Ingredient
-|-
`3 Tbsp (1.5 Tbsp)` | Dried Rosemary
`1/4 c  (2   Tbsp)` | Dried granulated garlic

### Hardware

Qty | Equipment
-|-
`1`     | Oven
`1`     | Kitchen scale
`1`     | Probe thermometer
`2 or 4 (1 or 2)`* | Loaf pans
`1`     | Mixing bowl
`2 (1)` | Containers with lids for dough refrigeration (e.g. mixing bowl, pot with lid, etc)
`1`     | Rimmed baking sheet or any other pan with sides (to hold water for baking)
`1`     | Sharp blade: e.g. razor, X-ACTO, paring knife
`1`     | Kettle or device to boil 2 qt water**
`2 (1)` | (Optional) Parchment paper sheet for lining loaf pan***
`1`     | (Optional) Silicone coated flipper
`2 (1)` | Sheet of foil**

\* If using the double-pan method, you will need two pans per loaf so one can serve as a lid.

** Required if _not_ using the double-pan method.

\*** ___Never___ use wax paper instead of parchment paper when baking - unless you like the taste of crayons.

#### `#ifndef STAND_MIXER` If Not Using Stand Mixer

- Dough scraper
- Surface for kneading

#### `#ifdef STAND_MIXER` If Using Stand Mixer

- Dough hook attachment

## Process

### Day 0

'Day 0' is necessary if your starter is a little sleepy or sad.

#### Evening 0

If your starter is in the fridge, give it a little boost by feeding it to reawaken it. See my process for [reactivating starter](#reactivating-starter).

### Day 1

#### Morning 1

1. Feed starter one last time to make the [levain](#reactivating-starter). Mix a tablespoon or so of your reawakened starter with 120 g (or 60 g for one loaf) each of water and flour.

#### Evening 1

1. Mix starter + water well.

1. Add flour and mix until it turns to a blob. __Note:__ Do not add salt at this time. See resource on [autolyse](#resources).

1. Cover bowl and let it sit for 1 - 2 hr (autolyse step).

1. Mix in salt* and knead.

   `#ifndef STAND_MIXER` __If Not Using Stand Mixer__
   - Wet your hands and knead for 5 minutes or as long as you can stand.
   - Use the dough scraper to scrape up bits if they get stuck on the surface.
   - Many resources suggest avoiding a floured work surface to prevent a tough loaf. However, I have used flour when my dough was over-hydrated or my starter wasn't mature enough, making the dough stringy and sticky. Avoid flouring if possible, but you probably won't ruin the loaf if you do.

   `#ifdef STAND_MIXER` __If Using Stand Mixer__
   - Use the dough hook attachment.
   - Knead on level 2/10 for 20-30 minutes.

   *\ For the everything bagel variation, add the bagel seasoning instead of the salt. For the rosemary garlic variation, add the rosemary and garlic at this time.

1. Repeat `3x`.
   1. Cover bowl for 30 minutes.
   1. 'Stretch and Fold'. See [note](#stretch-and-fold-in-mixing-bowl).

      `#ifdef STAND_MIXER` __The lazy method__
      1. If using a stand mixer, you can 'stretch and fold' by leaving the dough in the mixer and just knead it with the dough hook for 30-60 seconds.

      `#else` __Or__
      1. Using the rubber flipper, scoop up dough from side of the bowl
         and fold it into the center.
      1. Turn the bowl 90 degrees and repeat for 2 - 3 full rotations.

1. Split dough in half (for two loaves), and put each dough ball into a
   container for overnight refrigeration. __Note:__ If making 2 loaves,
   you can also split the dough after refrigeration.

1. Refrigerate overnight.

### Day 2

#### Morning 2

1. Remove dough from refrigerator.
1. (Optional) Line each loaf pan with parchment paper.
1. For each dough ball:
   1. Shape by stretching and folding dough into itself until you have a smooth oblong sphere.
   1. Place smoothed dough ball into loaf pan.

   __Note:__ I shape the dough in my hands without using a surface to minimize cleanup.

1. Put loaf pans into cold oven.
1. Go to work or get on with your day.

#### Evening 2

1. After 8 - 12 hours, remove loaf pans from oven.
1. Score loaves with sharp blade.

   __Notes:__
   -  With this method, the dough might have formed a skin.
     Ensure that you break through this skin when scoring.
   - I use an X-ACTO knife to score; you can also use a lame.

1. Put one oven rack on the bottom part of the oven, and one rack in the
   middle.
1. __If _not_ using double pan method:__
   1. Put baking sheet on the bottom rack.
   1. Boil `2 qt` water.
   1. Fill baking sheet with water
   (don't let it overflow).
4. __If using double pan method:__ To create a steam chamber, stack one pan upside-down over each loaf.
5. Place the loaf pans on the middle rack in a cold oven see [note](#avoid-a-tough-bottom-crust).
6. Preheat oven to 425 degrees Fahrenheit. See [note](#avoid-a-tough-bottom-crust).
7. __If _not_ using double pan method:__ If after 25 minutes, if the crust is already brown, cover each loaf
   with foil.
8. __If using double pan method:__ Remove top pan after 45 minutes.
9. Bake for another 5-15 minutes or until the internal temperature of bread is
   205 - 210 degrees Fahrenheit.
10. Remove each bread loaf from oven and pan.
11. Let it cool (or don't 😅) and cut it in half to view the beautiful
   crumb.

## Notes On My Process

### Avoid a Tough Bottom Crust

The crust of my bread used to be so tough it was hard to cut through; I actually burned out my electric knife. I have since modified my process to avoid a thick, difficult bottom.

#### Cold Start

I find that starting bread in a cold oven prevents the bottom crust from becoming too tough.

#### Oven Temperature

I use a lower temperature than many recipes call for. While common instructions suggest starting at 500°F and dropping to 450°F, I found those settings made the crust too hard. I get great results using 425°F.

### No Special Equipment

In the interest of workflow optimization, I choose to skip specialized equipment like Dutch ovens, bannetons, and flour towels. I prefer a streamlined process that minimizes maintenance and cleanup.

#### Loaf Pans

I like the having uniformly sized slices, so I prefer to bake my bread using loaf pans.

#### No Dutch Oven

To simplify my process, I replaced my Dutch oven with a double-pan method. I previously placed my loaf pans inside a Dutch oven, but the dough would often rise into the lid and scorch. Stacking two loaf pans creates the necessary steam while providing enough overhead space for the bread to grow.

#### No Flour Towels

In a household with pets, I prefer using plates or lids rather than cloth to cover my dough. This ensures a clean environment and provides a reliable seal for the refrigerator.

#### No Banneton Baskets

To streamline my workflow and cleanup, I keep my setup simple and skip the bannetons. It’s one less piece of equipment to maintain.

### Methodology

#### 'Stretch and Fold' in Mixing Bowl

To further simplify the process, I now use a stand mixer for 60 seconds instead of manual folding. Stretching and folding in the bowl with a spatula or using the traditional hand method works just as well.

#### Cold Filtered Water

While I once meticulously heated my water, I find cold filtered water works just as well. Just ensure it is filtered; chlorine in tap water can hinder your starter’s development.

### Starter Maintenance

I try to maintain a minimal amount of starter, and reduce the amount of
discard I collect.

#### Restarting After A Loaf

When making a loaf of bread and I transfer the starter to the main
mixing bowl, I save the bowl with the starter remnants and:

1. Scrape the remnants of the starter from the sides of the bowl.
1. Mix the starter remnants with a small, roughly equal amount of flour and water (about 5–10 g). I don’t measure; I just aim for a thick pancake batter consistency.
1. Transfer to a clean jar and put back in the fridge.

#### Reactivating Starter

I keep my starter in the fridge, so I usually reactivate the starter with a small feeding, then I make a [levain](https://amybakesbread.com/beginner-guide-sourdough-starter-and-levain/) the next morning. This is the process I follow:

Mix together

- 1/2 tsp starter from fridge
- 1.5 tsp water
- 1 Tbsp flour

Let it sit on the counter overnight. In the morning, add 150 g (or 75 g for one loaf) each of flour and filtered water (1/2 c + 2 Tbsp water by volume). After 6–10 hours, the starter is ready; I use the entire contents for the recipe.

## Resources

[What is an autolyse?](https://www.kingarthurbaking.com/blog/2017/09/29/autolyse-sourdough#what-is)

[How and why to make levain](https://amybakesbread.com/beginner-guide-sourdough-starter-and-levain/)
