---
title: Dairy Free Oreo Cream Pie
subtitle: Who knew Oreos were dairy free?
toc: true
toc-depth: 6
---
<!--___________________________________________________________________|
|______________________________________________________________________|
|        _   __   _   _ _   _   _   _         _                        |
|   |   |_| | _  | | | V | | | | / |_/ |_| | /                         |
|   |__ | | |__| |_| |   | |_| | \ |   | | | \_                        |
|    _  _         _ ___  _       _ ___   _                    / /      |
|   /  | | |\ |  \   |  | / | | /   |   \                    (^^)      |
|   \_ |_| | \| _/   |  | \ |_| \_  |  _/                    (____)o   |
|______________________________________________________________________|
|______________________________________________________________________|
|                                                                      |
|----------------------------------------------------------------------|
|   Copyright 2026, Rebecca Rashkin                                    |
|   -------------------------------                                    |
|   This code may be copied, redistributed, transformed, or built      |
|   upon in any format for educational, non-commercial purposes.       |
|                                                                      |
|   Please give me appropriate credit should you choose to use this    |
|   resource. Thank you :)                                             |
|----------------------------------------------------------------------|
|                                                                      |
|______________________________________________________________________|
|   //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\   |
|____________________________________________________________________-->
<!--DESCRIPTION
|   Oatmeal cream pies
|____________________________________________________________________-->


## Hardware
Qty | Equipment
-|-
`1` | Food processor
`1` | Mixing bowl
`1` | Whisk
`1` | Pie pan
`1` | Sauce pan

## Software

### Crust

Qty | Ingredient
-|-
`20-24 (2 sleeves)`   | Oreos (finely crushed)
`~4 Tbsp`             | Water

### Filling

Qty | Ingredient
-|-
`16 oz`   | White sweet potatoes, diced
`1 c`     | Cashews - this contributed to a very rich filling, I might try 1/2 c next time
`1 c`     | Coconut milk
`1/2 c`   | Egg white
`1/4 c`   | Maple syrup
`1/2`     | Lemon (juice)
`1/2 c`   | Sugar
`1/2 c`   | Vanilla protein or collagen powder
`10-12`   | Oreos broken into chunks

### (Optional) Topping

Qty | Ingredient
-|-
`1-3`   | Oreos, finely crushed (reserved from crust preparation)
`1/4 c` | Dairy-free yogurt or sour cream
`2 Tbsp`| Powdered sugar

## Procedure

1. Boil 2–3 cups of water, pour over cashews, and soak for 1 hour.
1. Boil the sweet potatoes for 10–15 minutes.
1. Preheat the oven to 350°F.
1. Pulverized Oreos into fine crumbs for the crust. Reserve 1 Tbsp for the topping.
1. Mix 4 Tbsp water into the Oreo crumbs.
1. Press the mixture into the bottom and sides of a pie pan.
1. Puree the sweet potatoes with the coconut milk, sugar, maple syrup, lemon juice, and salt.
1. Rinse the soaked cashews and puree for 5 minutes, scraping the sides periodically, until a smooth paste forms.
1. Fold the cashew paste into the sweet potato puree; once cooled to room temperature, whisk in the egg white and protein powder.
1. Fold in the broken Oreos and pour the mixture into the crust.
1. Bake at 350°F for 1 hour.
1. Chill the pie before serving.
1. (Optional) For the topping, mix the powdered sugar and yogurt. Spread the mixture over the top of the pie. Sprinkle with the finely crushed Oreos.