---
title: Sourdough Oatmeal Cream Pies
subtitle: 😋
toc: true
toc-depth: 6
---
<!--___________________________________________________________________|
|______________________________________________________________________|
|        _   __   _   _ _   _   _   _         _                        |
|   |   |_| | _  | | | V | | | | / |_/ |_| | /                         |
|   |__ | | |__| |_| |   | |_| | \ |   | | | \_                        |
|    _  _         _ ___  _       _ ___   _                    / /      |
|   /  | | |\ |  \   |  | / | | /   |   \                    (^^)      |
|   \_ |_| | \| _/   |  | \ |_| \_  |  _/                    (____)o   |
|______________________________________________________________________|
|______________________________________________________________________|
|                                                                      |
|----------------------------------------------------------------------|
|   Copyright 2026, Rebecca Rashkin                                    |
|   -------------------------------                                    |
|   This code may be copied, redistributed, transformed, or built      |
|   upon in any format for educational, non-commercial purposes.       |
|                                                                      |
|   Please give me appropriate credit should you choose to use this    |
|   resource. Thank you :)                                             |
|----------------------------------------------------------------------|
|                                                                      |
|______________________________________________________________________|
|   //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\  //\^.^/\\   |
|____________________________________________________________________-->
<!--DESCRIPTION
|   Oatmeal cream pies
|____________________________________________________________________-->


## Hardware
Qty | Equipment
-|-
`1` | Baking Scale
`1` | Whisk
`1` | Spatula
`1` | 2 TBS Cookie Scoop, #24, or a spoon
`2` | Large Baking Sheets

## Software

### Sourdough Oatmeal Cookies

Qty | Ingredient
-|-
`1 c`     | Unsalted Butter, 2 sticks or 1 cup
`225 g`   | Rolled Oats, Quick oats or old-fashioned rolled oats
`150 g`   | All-purpose flour
`1/2 tsp` | Salt
`1/2 tsp` | Ground cinnamon
`1/2 tsp` | Baking soda
`1 1/4 c` | Granulated Sugar
`2        | Eggs
`2 Tbsp`  | Maple syrup
`2/3 c`   | Sourdough discard, or active starter
`2 tsp`   | Vanilla extract

### Filling

`1 c`    | Softened cream cheese
`3 Tbsp` |  Unsalted Butter, softened
1/8 tsp` | pinch Kosher Salt
`1 tsp`  | Vanilla Extract
`300 g`  | Powdered Sugar, sifted if clumpy

## Procedure
1. Add both sticks of butter to a small saucepan and set over medium heat. Swirl the pan as the butter melts and starts to foam, a few minutes.With a spatula, constantly stir the butter (it can burn quickly!) until the solids brown and it takes on a fragrant popcorn-like aroma.

1. Transfer to a large bowl to cool to room temperature.


If you’re using quick oats, you can whisk all of your dry ingredients together in a bowl. If using old-fashioned rolled oats, add all of the dry ingredients to a food processor and pulse it a few times to break the oats apart into a crumbly mixture.Set aside.225 g Rolled Oats, 150 g All-purpose flour, ½ tsp Kosher Salt, ½ tsp Ground Cinnamon, ½ tsp Baking Soda

1. Whisk sugar, eggs, maple syrup with melted butter.

1. Add sourdough discard and vanilla extract and whisk to combine.

1. Add dry ingredients to wet ingredient mixture. Mix until no flour is visible.

1. Preheat the oven to 350ºF (177ºC) and line baking sheets with parchment paper or silicone baking mats.Use a 2 TBS cookie scoop or spoon to portion out about 26-28 equal-sized cookies (about 34g each if you want to be exact) and space them a few inches apart on the baking sheets.Bake one sheet at a time for 13-15 minutes, or until the cookies spread and the edges just start to brown. Don’t overcook or your cookies will be crisp (you want soft and chewy!).Cool on the baking sheets for 5 minutes before transferring to cool completely on wire racks.

1. Combine softened cream cheese, butter, salt, and vanilla extract. Whisk until light and fluffy.
1. Add powdered sugar (sift if it’s clumpy) and mix together until thick, smooth, and creamy like frosting.
2. Add milk if the mixture is too thick. Add more sugar if its too thin.
1. Let cookies cool. Spoon or pipe frosting onto one cookie, then add another cookie on top to make a sandwich. Repeat for all cookies.